import random
import json
import asyncio

import cacobot.base as base

@base.postcommand
async def woah(message, client):
    c = message.content.lower()
    send = None
    if message.author.id != client.user.id:
        if c == 'woah' or\
                c == 'woah.' or\
                c == 'whoa' or\
                 c == 'whoa.':
            send = 'Hey guys.'
        elif c == 'hey guys' or c == 'hey guys':
            send = 'Welcome to EB Games.'
        elif 'call of duty' in c or\
                'advanced warfare' in c or\
                'xbox one' in c:
            send = 'Copy that.'

    if send:
        if random.randint(1, 20) == 1:
            await client.send_message(message.channel, send)

@base.postcommand
async def wow(message, client):
    c = message.content.lower()
    if message.author.id != client.user.id:
        if c == 'wow' or c == 'wow.':
            if random.randint(1, 20) == 1:
                await client.send_message(
                    message.channel,
                    'Ethan, great moves. Keep it up. I\'m proud of you.'
                    )

suicides = [
    'Looks like Team %k is blasting off again!',
    '%k divided by 0.',
    '%k lost at Russian Roulette.',
    '%k applied for release.',
    '%k commited thoughtcrime.',
    '%k is ded.',
    '%k has died.',
    '%k has commited suicide.',
    '%k left it to the RNG.',
    '%k hugged Pyrope.',
    '%k had a whoopsie.',
    '%k failed at life.',
    '%k killed %hself.',
    '%k got too many student loans.',
    '%k is in debt.',
    '%k fell out of the world.',
    '%k had a bad time.',
    '%k had a bed tem.',
    '%k got dunked on.',
    '%k commited sudoku.',
    '%k commited seppuku.',
    '%k decided to end it once and for all.',
    '%k forgot to list a target\'s name.',
    '%k inched closer towards a black hole.',
    '%k discovers the secret to exploding your own brain.',
    '%k slits their own throat.',
    '%k bleeds out of a stab wound.',
    '%k died of dysentary.',
    '%k decided that %g had nothing left to live for.',
    '%k accidentally opened a letter bomb that had been returned to the sender.',
    '%k pulls the pin from a grenade without throwing it.',
    '%k ingested cyanide.',
    '%k looked down the barrel while firing.',
    '%k shot their chin.',
    '%k fired a blank to the head to prove that blanks are safe.',
    '%k "discovers middle earth" by jumping into a volcano.',
    '%k dies of lung cancer after smoking too much.',
    '%k starts smoking.',
    '%k dies from morbid obesity after eating so much.',
    '%k runs out of Psions after casting too many spells.',
    '%k falls into a strong river and drowns.',
    '%k gets ditched by Jerry.',
    '%k is murdered by a flower.',
    '%k accidentally wipes their save file.',
    '%k does not see a car coming and gets hit.',
    'A meteor falls from the sky and strikes %k, killing %h.',
    '%k finds some mercury and ingests it, leading to illness and death.',
    '%k decides to hug a bomb.',
    '%k steps into a bear trap and does not get rescued, being left to die alone.',
    '%k had the functions of every hole in %p face shuffled.',
    '%k was erradicated by Bill Cipher.',
    '%k discovers the joy of painting.',
    '%k could not think of anything.',
    '%k was contemplating what to do in life when a news feed item popped up, the contents of which gave %h an existential crisis. Not wanting to lose hope, %g continued to persevere, but to no avail. %k was seen standing at the top of a skyscraper, looking down at the city below. No other emotion besides sorrow for the universe was present as %g stepped off, before being rescued by a sudden shift in winds knocking %h back into a lower floor of the building. This did not stop %h as %g pulled out a gun and shot %hself in the head, ending it once and for all. Or so %g thought. The bullet had penetrated the brain but only caused %h to be in a vegetative state. The rest of %p sad life is now spent alone in a hospital with no family or friends, hooked up to machines and unable to do anything, before dying of old age and leaving this mortal coil forever.',
    'TODO: Death message for %k here.',
    '%k was looking good until %g killed %hself!',
    '%k suicides.',
    '%k fell too far.',
    '%k was squished.',
    '%k tried to leave.',
    '%k can\'t swim.',
    '%k mutated.',
    "%k melted.",
    "%k went boom.",
    "%k stood in the wrong spot.",
    "%k should have stood back.",
    "%k should have stood back.",
    "%k killed %hself.",
    '%k was killed by the power of voodoo.',
    '%k was punched by a Revenant.',
    '%k was slashed by an Imp.',
    '%k got too close to a Cacodemon.',
    '%k was bit by a Demon.',
    '%k was eaten by a spectre.',
    '%k was ripped open by a Baron of Hell.',
    '%k was gutted by a Hell Knight.',
    "%k was killed by a zombieman.",
    "%k was shot by a sergeant.",
    "%k was incinerated by an archvile.",
    "%k couldn't evade a revenant's fireball.",
    "%k was squashed by a mancubus.",
    "%k was perforated by a chaingunner.",
    "%k was spooked by a lost soul.",
    "%k was burned by an imp.",
    "%k was smitten by a cacodemon.",
    "%k was bruised by a Baron of Hell.",
    "%k was splayed by a Hell Knight.",
    "%k stood in awe of the spider demon.",
    "%k let an arachnotron get %h.",
    "%k was splattered by a cyberdemon.",
    "%k was mauled by a dog.",
    "%k was pecked to death.",
    "%k was charred by a weredragon.",
    "%k was slashed by a sabreclaw.",
    "%k was scalded by D'Sparil's serpent.",
    "%k was chewed up by D'Sparil's serpent.",
    "%k was no match for D'Sparil.",
    "%k was smacked down by D'Sparil.",
    "%k was scarred by a gargoyle.",
    "%k was hacked by a gargoyle.",
    "%k was devastated by an ironlich.",
    "%k got up-close and personal with an ironlich.",
    "%k was axed by an undead warrior.",
    "%k was slain by an undead warrior.",
    "%k was smashed by a golem.",
    "%k was shrieked to death by a nitrogolem.",
    "%k was rattled by an ophidian.",
    "%k was cursed by a wizard.",
    "%k was palpated by a wizard.",
    "%k tasted an Afrit's fire.",
    "%k was scalded by a Serpent.",
    "%k was poisoned by a Serpent.",
    "%k was mashed by an Ettin.",
    "%k was cut up by a Centaur.",
    "%k was cut up by a Slaughtaur.",
    "%k was struck down by a Slaughtaur's fireball.",
    "%k succumbed to a Bishop's dark power.",
    "%k was frozen solid by a Wendigo.",
    "%k was mauled by a Stalker.",
    "%k was melted by a Stalker.",
    "%k was charred by a Reiver.",
    "%k had %p life stolen by a Reiver.",
    "%k was incinerated by the Death Wyvern.",
    "%k was swept from the board by Korax.",
    "%k was slain by Zedek.",
    "%k couldn't absorb Menelkir's Mana.",
    "%k was baptized by Traductus.",
    "%k had %p bones rolled by the Heresiarch.",
    "%k was zealously shot down by an Acolyte.",
    "%k should have never rebelled against Macil.",
    "%k was gunned down by a Rebel.",
    "%k was beaten to death by the poor.",
    "%k should have never picked a fight with a civilian.",
    "%k was struck down by the Spectre.",
    "%k felt the wrath of The One God.",
    "%k couldn't escape from the Lore Master's grasp.",
    "%k was deleted by the Programmer.",
    "%k was blown away by the Bishop.",
    "%k was shot down by a Sentinel.",
    "%k was swept away by a Crusader.",
    "%k was sentenced by an Inquisitor.",
    "%k was bugged by a Stalker.",
    "%k triggered the automatic defenses.",
    "%k was clawed by a Templar.",
    "%k was vaporized by a Templar.",
    "%k was sliced open by a Reaver.",
    "%k was shot down by a Reaver.",
    "%k was telefragged.",
    "%k checks %p glasses.",
    "%k was slimed by a flemoid.",
    "%k was slimed by a bipedicus.",
    "%k was slimed by an armored bipedicus.",
    "%k was slimed by a cycloptis.",
    "%k was defeated by the Flembrane.",
    '%k ascended.',
    '%k was lost in the matrix.',
    '%k was digitized to see the MCP.',
    'I\'m afraid I can\'t do that, %k.'
]

killmsgs = [
    "%o was spoon fed by %k.",
    '%k tried PK Fire Ω!\n%o took mortal damage!',
    "%o was thouroughly mixed with %k's bootspork.",
    "%o was zorched by %k.",
    "%o was hit by %k's mega-zorcher.",
    "%o was rapid zorched by %k.",
    "%o was zorched by %k's propulsor.",
    "%o was hit by %k's propulsor.",
    "%o was phase zorched by %k.",
    "%o fell prey to %k's LAZ device.",
    "%o was lazzed by %k.",
    "%o chewed on %k's fist.",
    "%o was mowed over by %k's chainsaw.",
    "%o was tickled by %k's pea shooter.",
    "%o chewed on %k's boomstick.",
    "%o was splattered by %k's super shotgun.",
    "%o was mowed down by %k's chaingun.",
    "%o rode %k's rocket.",
    "%o almost dodged %k's rocket.",
    "%o was melted by %k's plasma gun.",
    "%o was splintered by %k's BFG.",
    "%o couldn't hide from %k's BFG.",
    "%o was telefragged by %k.",
    "%o was railed by %k.",
    "%o was burned by %k's BFG.",
    "%o got staffed by %k.",
    "%o got a shock from %k's gauntlets.",
    "%o waved goodbye to %k's elven wand.",
    "%o was pegged by %k's ethereal crossbow.",
    "%o was blasted a new one by %k's dragon claw.",
    "%o got sent down under by %k's hellstaff.",
    "%o was scorched to cinders by %k's phoenix rod.",
    "%o was bounced by %k's firemace.",
    "%o got clapped by %k's charged staff.",
    "%o was bled dry by %k's gauntlets.",
    "%o was assaulted by %k's elven wand.",
    "%o was shafted by %k's ethereal crossbow.",
    "%o was ripped apart by %k's dragon claw.",
    "%k poured his hellstaff on %o.",
    "%o was burned down by %k's phoenix staff.",
    "%o was squished by %k's giant mace sphere.",
    "%o was beaten to a pulp by %k's bare fists.",
    "%o got the axe from %k.",
    "%o had %p head caved in by %k's hammer.",
    "%o's soul was forged anew by %k's hammer.",
    "%o was silenced by %k's mighty Quietus.",
    "%o got a mace to the face from %k.",
    "%o was bitten by %k's serpent staff.",
    "%o choked on %k's serpent staff.",
    "%o was lit up by %k's flames.",
    "%o was cleansed by %k's Wraithverge.",
    "%o took one too many sapphire beams from %k.",
    "%o was turned into a frosty fellow by %k.",
    "%o recieved a shocking revelation from %k.",
    "%o was wiped off the face of the universe by %k's Bloodscourge.",
    "%o was unwittingly backstabbed by %k.",
    "%o got bolted to the wall by %k.",
    "%o recieved a lethal dose of %k's wrath.",
    "%o was drilled full of holes by %k's assault gun.",
    "%o gulped down %k's missile.",
    "%o was inverted by %k's H-E grenade.",
    "%o took a flame bath in %k's phosphorous pyre.",
    "%o was barbecued by %k.",
    "%o was zapped by %k.",
    "%o was viciously vaporized by %k.",
    "%o bowed down to the sheer power of %k's Sigil.",
    'Looks like Team %o is blasting off again!'
    '%k blasted off Team %o again!',
    '%k taught %o the Dewey Decimal System.',
    '%o was taught the Dewey Decimal System by %k.',
    '%o was doomed to fall by %k.',
    '%o got unfollowed by %k.',
    '%k unfollowed %o.',
    '%o got unfriended by %k.',
    '%k unfriended %o.',
    '%o got Obama\'d by %k.',
    '%k Obama\'d %o.',
    '%k took %o to court.',
    '%o got taken to court by %k.',
    '%o got #YOLO\'d by %k.',
    '%k #YOLO\'d %o.',
    '%o got uninstalled by %k.',
    '%k uninstalled %o.',
    '%o got annoyed by %k.',
    '%k annoyed %o.',
    '%k beat %o at life.',
    '%o got beaten at life by %k.',
    '%o got bidden farewell to by %k.',
    '%k bid farewell to %o.',
    '%o got bought out by %k.',
    '%k bought out by %o.',
    '%o got attacked by %k.',
    '%k attacked %o.',
    '%o got baked by %k.',
    '%k baked %o.',
    '%o got Jason\'ed by %k.',
    '%k Jason\'ed %o.',
    '%o got touhou\'d by %k.',
    '%k touhou\'d %o.',
    '%o got billed by %k.',
    '%k billed %o.',
    '%o got slammed by %k.',
    '%k slammed %o.',
    '%o got jammed by %k.',
    '%k jammed %o.',
    '%o got audited by %k.',
    '%k audited %o.',
    '%o got shot by %k.',
    '%k shot %o.',
    '%o got bleached by %k.',
    '%k bleached %o.',
    '%o got blotted out by %k.',
    '%k blotted out %o.',
    '%o got bashed by %k.',
    '%k bashed %o.',
    '%o\'s skull got bashed in by %k.',
    '%k bashed in %o\'s skull.',
    '%o got betrayed by %k.',
    '%k betrayed %o.',
    '%o got crossed by %k.',
    '%k crossed %o.',
    '%o got crossed out by %k.',
    '%k crossed %o out.',
    '%o got boxed by %k.',
    '%k boxed %o.',
    '%o got boxed in by %k.',
    '%k boxed %o in.',
    '%o got crossbred by %k.',
    '%k crossbred %o.',
    '%o got cut down by %k.',
    '%k cut down %o.',
    '%o got booked by %k.',
    '%k booked %o.',
    '%o got burried by %k.',
    '%k burried %o.',
    '%o got disproved by %k.',
    '%k disproved %o.',
    '%o\'s existance got disproved by %k.',
    '%k disproved %o\'s existance.',
    '%o got taken to the pool by %k.',
    '%k took %o to the pool.',
    '%o got busted by %k.',
    '%k busted %o.',
    '%o got killed by %k.',
    '%k killed %o.',
    '%o got calculated by %k.',
    '%k calculated %o.',
    '%o got carved by %k.',
    '%k carved %o.',
    '%o got canvased over by %k.',
    '%k canvased over %o.',
    '%o got drunk by %k.',
    '%k drank %o.',
    '%o got eaten by %k.',
    '%k ate %o.',
    '%o got roasted by %k.',
    '%k roasted %o.',
    '%o got classified by %k.',
    '%k classified %o.',
    '%o got choked by %k.',
    '%k choked %o.',
    '%o got chewed by %k.',
    '%k chewed %o.',
    '%o got concentrated by %k.',
    '%k concentrated %o.',
    '%o got concatenated by %k.',
    '%k concatenated %o.',
    '%o got crashed into by %k.',
    '%k crashed into %o.',
    '%o got cracked by %k.',
    '%k cracked %o.',
    '%o got closed by %k.',
    '%k closed %o.',
    '%o got clutched by %k.',
    '%k clutched %o.',
    '%o got collapsed by %k.',
    '%k collapsed %o.',
    '%k showed %o the ancient arts of Shaolin Kung Fu.',
    '%o got shown the ancient arts of Shaolin Kung Fu by %k.',
    '%o got concluded by %k.',
    '%k concluded %o.',
    '%o got defenestrated by %k.',
    '%k defenestrated %o.',
    '%o got decided by %k.',
    '%k decided %o.',
    '%o got deserted by %k.',
    '%k deserted %o.',
    '%o got exposed to horrors by %k.',
    '%k exposed horrors to %o.',
    '%o got infected by %k.',
    '%k infected %o.',
    '%o got divided by %k.',
    '%k divided %o.',
    '%o got drained by %k.',
    '%k drained %o.',
    '%o got dripped by %k.',
    '%k dripped %o.',
    '%o got dropped by %k.',
    '%k dropped %o.',
    '%o got disliked by %k.',
    '%k disliked %o.',
    '%o got downvoted by %k.',
    '%k downvoted %o.',
    '%o got consecrated on by %k.',
    '%k consecrated on %o.',
    '%o got forbidden by %k.',
    '%k forbade %o.',
    '%o got downloaded by %k.',
    '%k downloaded %o.',
    '%o got uploaded by %k.',
    '%k uploaded %o.',
    '%o got installed by %k.',
    '%k installed %o.',
    '%o got consigned by %k.',
    '%k consigned %o.',
    '%o lost to %k.',
    '%o lost to %k at a Xiaolin Showdown.',
    '%o lost to %k at a tennis.',
    '%o lost to %k at a boxing match.',
    '%o lost to %k at Portal 2 Co-op.',
    '%o got sued by %k.',
    '%k sued %o.',
    '%o lost a lawsuit against %k.',
    '%k won a lawsuit against %o.',
    '%o got forgotten by %k.',
    '%k forgot about %o.',
    '%o got educated by %k.',
    '%k educated %o.',
    '%o got obfuscated by %k.',
    '%k obfuscated %o.',
    '%o got dusted by %k.',
    '%k dusted %o.',
    '%o got lasered by %k.',
    '%k lasered %o.',
    '%o got constituted by %k.',
    '%k constituted %o.',
    '%o got misconstrued by %k.',
    '%k misconstrued %o.',
    '%o got contradicted by %k.',
    '%k contradicted %o.',
    '%o got grinded by %k.',
    '%k grinded %o.',
    '%o got had by %k.',
    '%o got hit by %k.',
    '%k hit %o.',
    '%o got snapchatted by %k.',
    '%k snapchatted %o.',
    '%o got converged by %k.',
    '%k converged %o.',
    '%o got cooked by %k.',
    '%k cooked %o.',
    '%o got expanded by %k.',
    '%k expanded %o.',
    '%o got exploded by %k.',
    '%k exploded %o.',
    '%o got converted by %k.',
    '%k converted %o.',
    '%o got charged by %k.',
    '%k charged %o.',
    '%o got stumped by %k.',
    '%k stumped %o.',
    '%o got Trumped by %k.',
    '%k Trumped %o.',
    '%o got Drumpfed by %k.',
    '%k Drumpfed %o.',
    '%o got cheesed by %k.',
    '%k cheesed %o.',
    '%o got crushed by %k.',
    '%k crushed %o.',
    '%o got dealt with by %k.',
    '%k dealt with %o.',
    '%o got erased by %k.',
    '%k erased %o.',
    '%o got released by %k.',
    '%k released %o.',
    '%k applied for %o\'s release.',
    '%o got inlaid by %k.',
    '%k inlaid %o.',
    '%o got mispelled by %k.',
    '%k mispelled %o.',
    '%o got detached by %k.',
    '%k detached %o.',
    '%o got unpersoned by %k.',
    '%k unpersoned %o.',
    '%o got smitted by %k.',
    '%k smited %o.',
    '%o got dedded by %k.',
    '%k dedded %o.',
    '%o got MUDAMUDAMUDA\'d by %k.',
    '%k ORAORAORA\'d %o.',
    '%o got turned into a bagel sandwich by %k.',
    '%k turned %o into a bagel sandwich.',
    'Killed by %k, %o got.',
    '%o, %k killed.',
    '%o got murdered by %k.',
    '%k murdered %o.',
    '%o got brutally murdered by %k.',
    '%k brutally murdered %o.',
    '%o got interwoven by %k.',
    '%k interwove %o.',
    '%o got forcechoked by %k.',
    '%k forcechoked %o.',
    '%o got taken out to the ballgame by %k.',
    '%k took %o out to the ballgame.',
    '%o got drilled by %k.',
    '%k drilled %o.',
    '%o got empowered by %k.',
    '%k empowered %o.',
    '%o got faxed by %k.',
    '%k faxed %o.',
    '%o got fooled by %k.',
    '%k fooled %o.',
    '%o got filed by %k.',
    '%k filed %o.',
    '%o got AFK\'d by %k.',
    '%k AFK\'d %o.',
    '%o got ragequitted by %k.',
    '%k ragequitted %o.',
    '%o got tormented by %k.',
    '%k tormented %o.',
    '%o got knitted by %k.',
    '%k knitted %o.',
    '%o got evaporated by %k.',
    '%k evaporated %o.',
    '%o got fizzled by %k.',
    '%k fizzed %o.',
    '%o got flapped by %k.',
    '%k flapped %o.',
    '%o got folded by %k.',
    '%k folded %o.',
    '%o got verbed by %k.',
    '%k verbed %o.',
    '%o got knocked out by %k.',
    '%k knocked %o out.',
    '%o got Zandatsu\'d by %k.',
    '%k Zandatsu\'d %o.',
    '%o got guacamole\'d by %k.',
    '%k guacamole\'d %o.',
    '%o got road rollered by %k.',
    '%k road rollered %o.',
    '%o got butterfingered by %k.',
    '%o was taken into %k\'s van.',
    '%k took %o into their van.',
    '%k butterfingered %o.',
    '%o got blown up by %k.',
    '%k blew up %o.',
    '%o got clagged by %k.',
    '%k clagged %o.',
    '%o got clubbed by %k.',
    '%k clubbed %o.',
    '%o got spinjumped on by %k.',
    '%k spinjumped on %o.',
    '%o got poofed by %k.',
    '%k poofed %o.',
    '%o got composed by %k.',
    '%k composed %o.',
    '%o got decomposed by %k.',
    '%k decomposed %o.',
    '%o got Urban Dictionaried by %k.',
    '%k Urban Dictionaried %o.',
    '%o got wallhacked by %k.',
    '%k wallhacked %o.',
    '%o got terroristed by %k.',
    '%k terroristed %o.',
    '%o got hounded on by %k.',
    '%k hounded on %o.',
    '%o got RIPped on by %k.',
    '%k RIPped on %o.',
    '%o got SUPERHOTted by %k.',
    '%k SUPERHOTted %o.',
    '%o got goomba\'d by %k.',
    '%k goomba\'d %o.',
    '%o got Falcon Punched by %k.',
    '%k Falcon Punched $Y.',
    '%o got blazed by %k.',
    '%k blazed %o.',
    '%o got Chaos Sabred by %k.',
    '%k Chaos Sabred %o.',
    '%o got thrown into the underground by %k.',
    '%k threw %o into the underground.',
    '%o was splatted by %k.',
    '%k splatted %o.',
    '%o had the Kraken released upon %h by %k.',
    '%k released the Kraken upon %o.',
    '%o was defamed by %k.',
    '%k defamed %o.',
    '%o got failed by %k.',
    '%k failed %o.',
    '%o got Space Jammed by %k.',
    '%k Space Jammed %o.',
    '%o got Shrek\'d by %k.',
    '%k Shrek\'d %o.',
    '%o got Shrekt by %k.',
    '%k Shrekt %o.',
    '%o got Silverhorn Trident\'ed by %k.',
    '%k Silverhorn Trident\'ed %o.',
    '%o got air punched by %k.',
    '%k air punched %o.',
    '%o got air fried by %k.',
    '%k air fried %o.',
    '%o got drillkicked by %k.',
    '%k drillkicked %o.',
    '%k turned %o into a pachinko machine.',
    '%o was turned into a pachinko machine by %k.',
    '%o was made into a sequel by %k.',
    '%k made %o into a sequel.',
    '%o got formatted by %k.',
    '%k formatted %o.',
    '%o got technologic\'d by %k.',
    '%k technologic\'d %o.',
    '%o got monopolised by %k.',
    '%k monopolised %o.',
    '%o got blunderbussed by %k.',
    '%k blunderbussed %o.',
    '%k taught %o the joy of debt.',
    '%o learned about the joy of debt thanks to %k.',
    '%o got mach tornado\'d by %k.',
    '%k mach tornado\'d %o.',
    '%o got final smahed by %k.',
    '%k final smahed %o.',
    '%o got webbed by %k.',
    '%k webbed %o.',
    '%o got heaven-piercing drilled by %k.',
    '%k heaven-piercing drilled %o.',
    '%o got Shoryukened by %k.',
    '%k Shoryukened %o.',
    '%o got Hadoukened by %k.',
    '%k Hadoukened %o.',
    '%o got L-cancelled by %k.',
    '%k L-cancelled %o.',
    '%o got trophied by %k.',
    '%k trophied %o.',
    '%o got Triforce Slashed by %k.',
    '%k Triforce Slashed %o.',
    '%o got Aura Stormed by %k.',
    '%k Aura Stormed %o.',
    '%o got PK Starstormed by %k.',
    '%k PK Starstormed %o.',
    '%o got dunked on by %k.',
    '%k dunked on %o.',
    '%o got Galaxia Darknessed by %k.',
    '%k Galaxia Darknessed %o.',
    '%o got Volt Tackled by %k.',
    '%k Volt Tackled %o.',
    '%k used splash on %o! It was Super Effective!',
    '%o got splashed on by %k. It was Super Effective!',
    '%o got Omega Blitzed by %k.',
    '%k Omega Blitzed %o.',
    '%o got Kiwi Blitzed by %k.',
    '%k Kiwi Blitzed %o.',
    '%o got Primal Reverted by %k.',
    '%k Primal Reverted %o.',
    '%o got Hydro Cannoned by %k.',
    '%k Hydro Cannoned %o.',
    '%o got Stealth Rocked by %k.',
    '%k Stealth Rocked %o.',
    '%o got corrupted by %k.',
    '%k got corrupted by %o.',
    '%o got ragdolled by %k.',
    '%k ragdolled %o.',
    '%o got traded in by %k.',
    '%k traded in %o.',
    '%o got balled up by %k.',
    '%k balled %o up.',
    '%o got marinated by %k.',
    '%k marinated %o.',
    '%o got simmered by %k.',
    '%k simmered %o.',
    '%o got deposited by %k.',
    '%k deposited %o.',
    '%o got withdrawn by %k.',
    '%k withdrew %o.',
    '%o got deported by %k.',
    '%k deported %o.',
    '%o got slapped by %k.',
    '%k slapped %o.',
    '%o got Kamehameh\'d by %k.',
    '%k Kamehameha\'d %o.',
    '%o got fragged by %k.',
    '%k fragged %o.',
    '%o was ended by %k.',
    '%k ended %o.',
    '%o got Bing\'d by %k.',
    '%k Bing\'d %o.',
    '%o got Googled by %k.',
    '%k Googled %o.',
    '%o got unsubscribed to by %k.',
    '%k unsubscribed to %o.',
    '%o got hacked by %k.',
    '%k hacked %o.',
    '%o got 4chan\'d by %k.',
    '%k 4chan\'d %o.',
    '%o got annihilated by %k.',
    '%k annihilated %o.',
    '%o got decimated by %k.',
    '%k decimated %o.',
    '%o was drowned by %k.',
    '%k drowned %o.',
    '%o got hashtagged by %k.',
    '%k hashtagged %o.',
    '%o got whaled on by %k.',
    '%k whaled on %o.',
    '%k→%o %k→%o %k→%o %k→%o %k→%o %k→%o %k→%o %k→%o %k→%o ',
    '%o got Hamon\'d by %k.',
    '%k Hamon\'d %o.',
    '%o got hammed on by %k.',
    '%k hammed on %o.',
    '%o got denied by %k.',
    '%k denied %o.',
    '%o got hung by %k.',
    '%k hung %o.',
    '%o got eliminated by %k.',
    '%k eliminated %o.',
    '%o got delimited by %k.',
    '%k delimited %o.',
    '%o was added to the file by %k.',
    '%k added %o to the file.',
    '%o was 0x10c %k',
    '%k 0x10c %o',
    '%o got nidhogged by %k.',
    '%k nidhogged %o.',
    '%o got Steve\'d by %k.',
    '%k Steve\'d %o.',
    '%o got dined on by %k.',
    '%k dined on %o.',
    '%o got elbowed by %k.',
    '%k elbowed %o.',
    '%o got Tony Abboted by %k.',
    '%k Tony Abboted %o.',
    '%o got David Cameroned by %k.',
    '%k David Cameroned %o.',
    '%o got Donald Trumped by %k.',
    '%k Donald Trumped %o.',
    '%o got Donald Drumpfed by %k.',
    '%k Donald Drumpfed %o.',
    '@​%o got pinged by %k.'
    '%k pinged @%o.',
    '%o\'s streak was ended by %k.',
    '%k ended %o\'s streak.',
    '%o\'s game was ended by %k.',
    '%k ended %o\'s game.',
    '%o was charbroiled by %k.',
    '%k charbroiled %o.',
    '%o got despawned by %k.',
    '%k despawned %o.',
    '%o got bushwacked by %k.',
    '%k bushwacked %o.',
    '%o got sneezed on by %k.',
    '%k sneezed on %k.',
    '%o got heckled at by %k.',
    '%k heckled at %o.',
    '%o got coughed at by %k.',
    '%k coughted at %o.',
    '%o got signed out by %k.',
    '%k signed out %V.',
    '%o got sandwiched by %k.',
    '%k sandwiched %o.',
    '%o got swagged on by %k.',
    '%k swagged on %o.',
    '%o got dank memed by %k.',
    '%k dank memed %o.',
    '%o got evaluated by %k.',
    '%k evaluated %o.',
    '%o got ignited by %k.',
    '%k ignited %o.',
    '%o got oppressed by %k.',
    '%k oppresed %o.',
    '%o got operated by %k.',
    '%k operated %o.',
    '%o got overflowed by %k.',
    '%k overflowed %o.',
    '%o got pasted by %k.',
    '%k pasted %o.',
    '%o got pastad by %k.',
    '%k pastad %o.',
    '%o got spaghetti\'d by %k.',
    '%k spaghetti\'d %o.',
    '%o got prescribed by %k.',
    '%k prescribed %o.',
    '%o got denounced by %k.',
    '%k denounced %o.',
    '%o got taken out to dinner by %k.',
    '%k took %o out to dinner.',
    '%o got seperated by %k.',
    '%k seperated %o.',
    '%o got subtracted by %k.',
    '%k subtracted %o.',
    '%o got taxed by %k.',
    '%k taxed %o.',
    '%o got terminated by %k.',
    '%k terminated %o.',
    '%o got punctured by %k.',
    '%k puncutred %o.',
    '%o got brewed into a delicious cup of coffee by %k.',
    '%k brewed %o into a delicious cup of coffee.',
    '%o got taxidermied by %k.',
    '%k taxidermied %o.',
    '%o\'s throat is slit by %k.',
    '%k slits %o\'s throat.',
    '%o got stabbed by %k.',
    '%k stabbed %o.',
    '%o got shanked by %k.',
    '%k shanked %o.',
    '%o got rekt by %k.',
    '%k rekt %o.',
    '%o got owned by %k.',
    '%k owned %o.',
    '%o got pwned by %k.',
    '%k pwned %o.',
    '%o\'s organs were ripped out by %k.',
    '%k ripped out the organs of %o.',
    '%o got burned by %k.',
    '%k burned %o.',
    '%o got launched out of a cannon into the sun by %k.',
    '%k launched %o out of a cannon into the sun.',
    '%o got clocked on the head by %k.',
    '%k clocked %o on the head.',
    '%o got pushed into a tarpit by %k.',
    '%k pushed %o into a tarpit.',
    '%o got trapped in quicksand by %k.',
    '%k trapped %o in quicksand.',
    '%o got one-punched by %k.',
    '%k one-punched %o.',
    '%o got punched by %k.',
    '%k punched %o.',
    '%o got pasta machined by %k.',
    '%k pasta machined %o.',
    '%o got Aoshima\'d by %k.',
    '%k Aoshima\'d %o.',
    '%o got Wabisuke\'d by %k.',
    '%k Wabisuke\'d %o.',
    '%o got Gear Seconded by %k.',
    '%k Gear Seconded %o.',
    '%o got typoed by %k.',
    '%k typoed %o.',
    '%o got Spirit Bombed by %k.',
    '%k Spirit Bombed %o.',
    '%o got Who The Hell Do You Think I Am Kicked by %k.',
    '%k Who The Hell Do You Think I Am Kicked %o.',
    '%o got Jim Sterlinged by %k.',
    '%k Jim Sterlinged %o.',
    '%k Jim Fucking Sterling Sonned %o.',
    '%o got entropied by %k.',
    '%k entropied %o.',
    '%o got demolished by %k.',
    '%k demolished %o.',
    '%o got turned into poutine by %k.',
    '%k turned %o into poutine.',
    '%o got DENDRO\'d by %k.',
    '%k DENDRO\'d %o.',
    '%o got Azusayumi\'d by %k.',
    '%k Ayusayumi\'d %o.',
    '%o got Baryon Lanced by %k.',
    '%k Baryon Lanced %o.',
    '%o got cast jammed by %k.',
    '%k cast jammed %o.',
    '%o got Niflheimed by %k.',
    '%k Niflheimed %o.',
    '%o got Gram Demolitioned by %k.',
    '%k Gram Demolitioned by %o.',
    '%o got Lapised by %k.',
    '%k Lapised %o.',
    '%o got Pluto\'d by %k.',
    '%k Pluto\'d %o.',
    '%o got Inferno\'d by %k.',
    '%k Inferno\'d %o.',
    '%o got Napstablocked by %k.',
    '%k Napstablocked %o.',
    '%o was slain by %k.',
    '%o was bored to death by %k.',
    '%k bored %o to death.',
    '%o was baked into a pizza by %k.',
    '%k baked %o into a pizza.',
    '%o got sniped by %k.',
    '%k sniped %o.',
    '%o got piss thrown at by %k.',
    '%k threw piss at %o.',
    '%o got canned by %k.',
    '%k canned %o.',
    '%o got disemboweled by %k.',
    '%k disemboweled %o.',
    '%o was sent to %p grave by %k.',
    '%k sent %o to %p grave.',
    '%o was gnocchi\'d by %k.',
    '%k gnocchi\'d %o.',
    '%o was railway\'d by %k.',
    '%k railway\'d %o.',
    '%k played a blank card for %o.',
    '%o was oh\'d by %k.',
    '%k oh\'d %o.',
    '%o\'s killing spree was ended by %k'
]

def postify(phrase, message, pronouns):
    w = phrase.replace(
        '%k', message.author.name
        ).replace(
            '%g', pronouns['%g']
            ).replace(
                '%h', pronouns['%h']
                ).replace(
                    '%p', pronouns['%p']
                    )

    if message.mentions:
        w = w.replace(
            '%o', message.mentions[0].name
            )
    elif len(message.content.split()) > 1:
        w = w.replace(
            '%o', message.content.split(None, 1)[1]
        )

    return w

cooldown = False

@base.cacofunc
async def kill(message, client):
    '''
    **.kill** [ mention ]
    **.kill** [ optin ] [ he/she/they ] [ him/her/them ] [ his/her/their ]
    Prints an obituary for the mentioned party. By default, will use "They" pronouns. You can do `.kill optin 1 2 3` to opt into replacing your pronouns with 3 of your choice. The syntax is posted above. This is agnostic: You can use any word you want for a pronoun.
    *Examples: `.kill @BooBot`, `.kill optin schlee schlim schleir`*
    '''
    # global cooldown
    cooldown = False

    try:
        with open('configs/pronouns.json') as datastream:
            optin = json.load(datastream)
    except FileNotFoundError:
        with open('configs/pronouns.json', 'w') as datastream:
            datastream.write('{}')
        optin = {}

    params = message.content.split()
    pronouns = {'%g':'they', '%h':'them', '%p': 'their'}

    if message.mentions and message.mentions[0].id in optin:
        pronouns = optin[message.mentions[0].id]
    elif len(message.content.split()) > 1 and [x for x in message.server.members if x.name == message.content.split(None, 1)[1]] and [x.id for x in message.server.members if x.name == message.content.split(None, 1)[1]][0] in optin:
        pronouns = optin[[x for x in message.server.members if x.name == message.content.split(None, 1)[1]][0]]

    if len(params) < 2:
        if not cooldown:
            await client.send_message(message.channel, postify(random.choice(suicides), message, pronouns))
            cooldown = True
            await asyncio.sleep(5)
            cooldown = False
    elif message.mentions and message.mentions[0] == message.author:
        if not cooldown:
            await client.send_message(message.channel, postify(random.choice(suicides), message, pronouns))
            cooldown = True
            await asyncio.sleep(5)
            cooldown = False
    elif message.mentions:
        if not cooldown:
            await client.send_message(message.channel, postify(random.choice(killmsgs), message, pronouns))
            cooldown = True
            await asyncio.sleep(5)
            cooldown = False
    elif params[1] == 'optin':
        try:
            optin[message.author.id] = {
                '%g' : params[2],
                '%h' : params[3],
                '%p' : params[4]
            }
            with open('configs/pronouns.json', 'w') as datastream:
                json.dump(optin, datastream, indent=4)
            await client.send_message(message.channel, '{}: I have successfully updated your pronouns to {}/{}/{}.'.format(
                message.author.name,
                params[2],
                params[3],
                params[4]
                ))
        except IndexError:
            await client.send_message(message.channel, '{}: You must provide 3 pronouns as an analogue to "he/she/they", "him/her/them", and "his/her/their", in that order.'.format(message.author.name))
    elif [x for x in message.server.members if x.name == message.content.split(None, 1)[1]] and [x for x in message.server.members if x.name == message.content.split(None, 1)[1]][0] == message.author:
        if not cooldown:
            await client.send_message(message.channel, postify(random.choice(suicides), message, pronouns))
            cooldown = True
            await asyncio.sleep(5)
            cooldown = False
    elif '@everyone' in message.content:
        await client.send_message(message.channel, '{}: **Do not use this command to circumvent everyone mention restrictions.**'.format(message.author.name))
    else:
        if not cooldown:
            await client.send_message(message.channel, postify(random.choice(killmsgs), message, pronouns))
            cooldown = True
            await asyncio.sleep(5)
            cooldown = False
